include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/*.g.dart
    - lib/**/*.ast.gql.dart
    - lib/**/*.schema.gql.dart
    - lib/**/*.data.gql.dart
    - lib/**/*.req.gql.dart
    - lib/**/*.var.gql.dart
    - lib/**/*.gql.dart
    - lib/**/*.g.dart
    - lib/*.freezed.dart
    - lib/**/*.freezed.dart
    - lib/*.chopper.dart
    - lib/**/*.chopper.dart
    - lib/generated/*.dart
    - lib/generated/intl/*.dart
    - lib/plugins/i18n_generator/lib/*.dart
    - plugins/**
    - lib/**/generated_plugin_registrant.dart
    - lib/**/*.gr.dart
    - lib/**/*.config.dart
    - lib/firebase/**
    - lib/l10n/*.dart
    - lib/l10n/**/*.dart
  errors:
    missing_required_param: error
    invalid_assignment: warning
    missing_return: error
    dead_code: info
    todo: ignore
    invalid_annotation_target: ignore
    use_build_context_synchronously: ignore
    invalid_reference_to_generative_enum_constructor: ignore

linter:
  rules:
    # For Util classes and constants
    avoid_classes_with_only_static_members: false

    always_use_package_imports: true
    avoid_dynamic_calls: true
    avoid_types_as_parameter_names: true
    avoid_web_libraries_in_flutter: true
    use_key_in_widget_constructors: true
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    avoid_multiple_declarations_per_line: true
    eol_at_end_of_file: true

    # Make constructors the first thing in every class
    sort_constructors_first: true

    # Better readability
    always_specify_types: true
    omit_local_variable_types: false

    constant_identifier_names: true

    sort_child_properties_last: true
    unnecessary_brace_in_string_interps: true
    await_only_futures: true

    # If migrating from pedantic, add the ff rules down below
    prefer_single_quotes: true
    unawaited_futures: true
    unsafe_html: true
    use_full_hex_values_for_flutter_colors: true

    # We use 150 line characters
    # This will be setup on the formatter's code editor setups
    lines_longer_than_80_chars: false

    # As much as possible add const
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_const: true

    avoid_unused_constructor_parameters: false

    # use log instead of print
    avoid_print: true
